@task PDA-1314 Refactor API to include queue/topic configurations in …
parasoft/parasoft-demo-app pull request #188
Opened 2022-12-02 09:54 UTC by lli-parasoft

2022-12-02 10:11 UTC, rwang-parasoft requested changes

2022-12-02 10:11 UTC, rwang-parasoft commented on src/main/java/com/parasoft/demoapp/config/kafka/KafkaConfig.java
> +    public static final String ORDER_SERVICE_REQUEST = "inventory.request";
Add `DEFAULT_` prefix.

2022-12-02 10:11 UTC, rwang-parasoft commented on src/main/java/com/parasoft/demoapp/config/kafka/KafkaConfig.java
> +    @Getter private static final String inventoryServiceListenToQueue = ORDER_SERVICE_REQUEST;
Remove unnecessary code.

2022-12-02 10:11 UTC, rwang-parasoft commented on src/main/java/com/parasoft/demoapp/dto/GlobalPreferencesResponseDTO.java
> +    @Hidden
Remove unnecessary code.

2022-12-02 10:11 UTC, rwang-parasoft commented on src/main/java/com/parasoft/demoapp/dto/GlobalPreferencesResponseDTO.java
> +    @Schema(description = "Only works when useParasoftJDBCProxy field is enabled. Default value is http://localhost:9080 if this field is not set.")
Remove @Schema in GlobalPreferencesEntity since it GlobalPreferencesResponseDTO will replace it to export to API. Other properties as well.

2022-12-02 10:11 UTC, rwang-parasoft commented on src/main/java/com/parasoft/demoapp/dto/GlobalPreferencesResponseDTO.java
> +    private String orderServiceSendTo;
Add `activeMqConfig` property(the type should be `MqConfigDTO `) and put `orderServiceSendTo` and `orderServiceListenOn` into object of  `activeMqConfig` property.

2022-12-02 10:11 UTC, rwang-parasoft commented on src/main/java/com/parasoft/demoapp/model/global/preferences/GlobalPreferencesEntity.java
> +    private String orderServiceRequest;
Rename it to `orderServiceRequestTopic` and rename `orderServiceResponse` to  `orderServiceResponseTopic` , the  column names as well.

2022-12-02 10:11 UTC, rwang-parasoft commented on src/main/java/com/parasoft/demoapp/model/global/preferences/KafkaConfigEntity.java
> +public class KafkaConfigEntity {
Rename it to MqConfigDTO and move it to dto folder.

2022-12-02 10:11 UTC, rwang-parasoft commented on src/main/java/com/parasoft/demoapp/service/GlobalPreferencesDefaultSettingsService.java
> +    public String defaultOrderServiceRequest() {
Rename it to `defaultOrderServiceRequestTopic()` and rename `defaultOrderServiceResponse()` to `defaultOrderServiceResponseTopic()`.

2022-12-02 21:43 UTC, yshi-parasoft commented on src/main/java/com/parasoft/demoapp/dto/GlobalPreferencesResponseDTO.java
> +        this.getActiveMqConfig().setOrderServiceListenOn(globalPreferencesEntity.getOrderServiceDestinationQueue());
I think these two values need to be swapped at line 53 and 54.
![image](https://user-images.githubusercontent.com/35082985/205395149-afad2e31-c635-4b1c-994a-42863c6cf6fb.png)

2022-12-05 02:29 UTC, rwang-parasoft approved these changes

2022-12-05 02:29 UTC, merged