@task PDA-1410 Create bi-direactional method updateItemsInStock
parasoft/parasoft-demo-app pull request #256
Opened 2023-01-04 05:15 UTC by dtang-parasoft

2023-01-04 23:12 UTC, yshi-parasoft commented
Please merge conflict.
Also I just realized that we need to add log for exceptions. Please add log for this method and also help to add log for the other two existing methods for the JSON service.

2023-01-04 23:54 UTC, yshi-parasoft commented
I think we should handle the error case when the stock is already 0 and we performed a Deduction on it. 
Also did you test multi-thread situation? I didn't see any special handling for it and if not please research for possible issues.

2023-01-06 08:52 UTC, rwang-parasoft commented on src/main/java/com/parasoft/demoapp/messages/AssetMessages.java
> +	public static final String REQUEST_PARAMETER_CANNOT_BE_EMPTY="The request parameter cannot be empty.";
Change it to REQUEST_PARAMETER_CANNOT_BE_NULL and need to change the value.

2023-01-06 08:52 UTC, rwang-parasoft commented on src/main/java/com/parasoft/demoapp/grpc/service/JsonServiceImpl.java
> +            public void onNext(ItemRequest value) {
Rename the vaue itemRequest.

2023-01-06 08:57 UTC, rwang-parasoft commented on src/main/java/com/parasoft/demoapp/grpc/service/JsonServiceImpl.java
> +                        ParameterValidator.requireNonNull(value.getValue(), AssetMessages.IN_STOCK_CANNOT_BE_NULL);
Change the message to OPERATION_NUMBER_CANNOT_BE_NULL=The quantity for item inventory dedction or addition can not be null.

2023-01-06 08:58 UTC, rwang-parasoft commented on src/main/java/com/parasoft/demoapp/grpc/service/JsonServiceImpl.java
> +                            IncorrectOperationException incorrectOperationException =
Do not create a new IncorrectOperationException.

2023-01-06 09:42 UTC, rwang-parasoft approved these changes

2023-01-06 19:43 UTC, yshi-parasoft commented
The changes looks good. Please resolve conflict before merging.

2023-01-06 19:44 UTC, yshi-parasoft requested changes
The changes looks good. Except that I think we can change the object name to be "lock" instead of "clock". Also please resolve conflict before merging.

2023-01-08 19:38 UTC, yshi-parasoft approved these changes

2023-01-09 01:58 UTC, merged