@task PDA-1411 Add link and modal dialog for gRPC configuration detai…
parasoft/parasoft-demo-app pull request #258
Opened 2023-01-04 08:45 UTC by lli-parasoft

2023-01-04 22:37 UTC, yshi-parasoft commented on src/main/resources/i18n/aerospace/common.properties
> +GRPC_CONFIGURATION_DETAILS=GRPC Configuration Details
Please use `gPRC` instead of `GRPC`

2023-01-04 22:54 UTC, yshi-parasoft commented
Please follow the idea below to modify the content. We should also include description for Protobuf version.

The demo app comes with a JSON gRPC service which has the following configuration details:

Host: xxx
Port: xxx
Service Name: xxx

There is also a Protobuf version of the service with same methods:
Host: xxx
Port: xxx
Service Name: xxx

Here are the methods implemented in both service:

-------------------------------------------------------------------------------------------------------------------
|           Method           |         Description                                                                                                        |
--------------------------------------------------------------------------------------------------------------------
|  getStockByItemId     |  Unary call which sends item id and receives stock quantity                                    |
--------------------------------------------------------------------------------------------------------------------
|  getItemsInStock        |  Server streaming method which gets information of all items in stock in stream  |
--------------------------------------------------------------------------------------------------------------------
|  updateItemsInStock  |  Bidirectional streaming method which takes information to update item stock    |
|                                    |  and responds with updated item information                                                        |
--------------------------------------------------------------------------------------------------------------------

2023-01-05 10:14 UTC, rwang-parasoft requested changes
Need to change style of modal.

2023-01-06 01:15 UTC, yshi-parasoft commented
![image](https://user-images.githubusercontent.com/35082985/210909767-18887494-d48e-4293-bd49-faa9558f4124.png)
Should apply style to align left for method names to be consistent.

2023-01-06 01:16 UTC, yshi-parasoft commented
Also I think the service name for Protobuf is changed. Please update it.

2023-01-06 09:10 UTC, rwang-parasoft approved these changes

2023-01-06 19:15 UTC, yshi-parasoft commented on src/main/resources/static/common/js/demoAdmin.js
> +            demo.gRPCConfigurationJsonDetails = [
There are some UI lags when opening the modal dialog. I think the only information we need from the callback is the port. So please set other values before we make the API call and only set port value in the callback to improve the performance.

2023-01-06 19:16 UTC, yshi-parasoft requested changes
Please fix this before merging:
https://github.com/parasoft/parasoft-demo-app/pull/258/files#r1063712832

2023-01-09 06:19 UTC, merged