@task PDA-1192 Remove item stock from item table and move related operations to inventory service
parasoft/parasoft-demo-app pull request #79
Opened 2022-10-28 08:52 UTC by tren-parasoft

Remove item stock from item table and move related operations to inventory service

2022-10-28 09:57 UTC, rwang-parasoft requested changes
Need to modify code.

2022-10-28 09:58 UTC, rwang-parasoft commented on src/main/java/com/parasoft/demoapp/service/ItemInventoryService.java
> +
All changes need to add validations.

2022-10-28 09:59 UTC, rwang-parasoft commented on src/main/java/com/parasoft/demoapp/service/OrderService.java
> +    private ItemInventoryService itemInventoryService;
Introduce the itemInventoryService but doesn't use it, need to double check.

2022-10-28 22:11 UTC, yshi-parasoft commented on src/main/java/com/parasoft/demoapp/service/ItemService.java
> +        result.setInStock(itemInventoryService.saveItemInStock(result.getId(), result.getInStock()).getInStock());
"result" should already have the "inStock" property and no need to set again.

2022-10-31 07:12 UTC, rwang-parasoft approved these changes

2022-11-01 02:13 UTC, merged